CREATE DATABASE usc;
USE usc;

CREATE TABLE `careers` (
  `CAREER_ID` int NOT NULL AUTO_INCREMENT,
  `CAREER_NAME` varchar(255) NOT NULL,
  `CAREER_STATUS` tinyint NOT NULL DEFAULT '1',
  `CAREER_CREATION` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CAREER_LAST_UPDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CAREER_ID`),
  UNIQUE KEY `CAREER_NAME` (`CAREER_NAME`),
  CONSTRAINT `careers_chk_1` CHECK ((`CAREER_STATUS` in (0,1)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `certificate_fields` (
  `FIELD_ID` int NOT NULL AUTO_INCREMENT,
  `FIELD_NAME` varchar(255) NOT NULL,
  `FIELD_VALUE` varchar(255) NOT NULL,
  PRIMARY KEY (`FIELD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `people` (
  `PEOPLE_ID` int NOT NULL AUTO_INCREMENT,
  `PEOPLE_PREFIX` varchar(255) DEFAULT NULL,
  `PEOPLE_NAME` varchar(255) NOT NULL,
  `PEOPLE_CHARGE` varchar(255) NOT NULL,
  `PEOPLE_GENDER` tinyint NOT NULL,
  PRIMARY KEY (`PEOPLE_ID`),
  CONSTRAINT `people_chk_1` CHECK ((`PEOPLE_GENDER` in (0,1)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `students` (
  `STUDENT_ID` int NOT NULL AUTO_INCREMENT,
  `STUDENT_TUITION` int NOT NULL,
  `STUDENT_NAME` varchar(255) NOT NULL,
  `STUDENT_PA_LAST_NAME` varchar(255) DEFAULT NULL,
  `STUDENT_MA_LAST_NAME` varchar(255) DEFAULT NULL,
  `STUDENT_STATUS` tinyint NOT NULL DEFAULT '1',
  `STUDENT_CREATION` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `STUDENT_LAST_UPDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`STUDENT_ID`),
  UNIQUE KEY `STUDENT_TUITION` (`STUDENT_TUITION`),
  CONSTRAINT `students_chk_1` CHECK ((`STUDENT_STATUS` in (0,1)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `users` (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `USER_EMAIL` varchar(255) NOT NULL,
  `USER_PASSWORD` varchar(255) NOT NULL,
  `USER_ROLE` varchar(50) NOT NULL DEFAULT 'admin',
  `USER_STATUS` tinyint NOT NULL DEFAULT '1',
  `USER_CREATION` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `USER_LAST_UPDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_EMAIL` (`USER_EMAIL`),
  CONSTRAINT `users_chk_1` CHECK ((`USER_ROLE` in (_utf8mb4'admin',_utf8mb4'superAdmin'))),
  CONSTRAINT `users_chk_2` CHECK ((`USER_STATUS` in (0,1)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `subjects` (
  `SUBJECT_ID` int NOT NULL AUTO_INCREMENT,
  `CAREER_ID` int NOT NULL,
  `SUBJECT_NAME` varchar(255) NOT NULL,
  `SUBJECT_PERIOD` int NOT NULL,
  `SUBJECT_STATUS` tinyint NOT NULL DEFAULT '1',
  `SUBJECT_CREATION` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `SUBJECT_LAST_UPDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`SUBJECT_ID`),
  KEY `CAREER_ID` (`CAREER_ID`),
  CONSTRAINT `subjects_ibfk_1` FOREIGN KEY (`CAREER_ID`) REFERENCES `careers` (`CAREER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `subjects_chk_1` CHECK ((`SUBJECT_PERIOD` between 1 and 9)),
  CONSTRAINT `subjects_chk_2` CHECK ((`SUBJECT_STATUS` in (0,1)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `scores` (
  `SCORE_ID` int NOT NULL AUTO_INCREMENT,
  `STUDENT_ID` int NOT NULL,
  `SUBJECT_ID` int NOT NULL,
  `SCORE` int NOT NULL,
  `SCORE_OBSERVATION` varchar(255) DEFAULT NULL,
  `SCORE_STATUS` tinyint NOT NULL DEFAULT '1',
  `SCORE_CREATION` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `SCORE_LAST_UPDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`SCORE_ID`),
  KEY `STUDENT_ID` (`STUDENT_ID`),
  KEY `SUBJECT_ID` (`SUBJECT_ID`),
  CONSTRAINT `scores_ibfk_1` FOREIGN KEY (`STUDENT_ID`) REFERENCES `students` (`STUDENT_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `scores_ibfk_2` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `subjects` (`SUBJECT_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `scores_chk_1` CHECK ((`SCORE` between 0 and 10)),
  CONSTRAINT `scores_chk_2` CHECK ((`SCORE_OBSERVATION` in (_utf8mb4'EX',_utf8mb4'TS',_utf8mb4'EQ',_utf8mb4'REC',_utf8mb4'ex',_utf8mb4'ts',_utf8mb4'eq',_utf8mb4'rec'))),
  CONSTRAINT `scores_chk_3` CHECK ((`SCORE_STATUS` in (0,1)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `students_careers` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `STUDENT_ID` int NOT NULL,
  `CAREER_ID` int NOT NULL,
  `START_DATE` date NOT NULL,
  `END_DATE` date NOT NULL,
  `RELATION_STATUS` tinyint NOT NULL DEFAULT '1',
  `CREATION` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_UPDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `STUDENT_ID` (`STUDENT_ID`),
  KEY `CAREER_ID` (`CAREER_ID`),
  CONSTRAINT `students_careers_ibfk_1` FOREIGN KEY (`STUDENT_ID`) REFERENCES `students` (`STUDENT_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `students_careers_ibfk_2` FOREIGN KEY (`CAREER_ID`) REFERENCES `careers` (`CAREER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `students_careers_chk_1` CHECK ((`RELATION_STATUS` in (0,1)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;