USE usc;

INSERT INTO careers (CAREER_NAME, CAREER_STATUS, CAREER_CREATION, CAREER_LAST_UPDATE) VALUES
('LICENCIATURA EN INGENIERÍA EN SISTEMAS COMPUTACIONALES', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('LICENCIATURA EN ADMINISTRACIÓN DE EMPRESAS', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('LICENCIATURA EN ARQUITECTURA', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('LICENCIATURA EN CONTADURIA PUBLICA', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('LICENCIATURA EN DERECHO', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('LICENCIATURA EN DISEÑO GRÁFICO', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('LICENCIATURA EN INFORMÁTICA ADMINISTRATIVA', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('LICENCIATURA EN TRABAJO SOCIAL', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

SELECT * FROM careers;