USE usc;

INSERT INTO certificate_fields (FIELD_NAME, FIELD_VALUE) VALUES
('RÉGIMEN', 'PARTICULAR'),
('TURNO', 'MIXTO'),
('CLAVE', '07PSU0063R'),
('MODALIDAD', 'MIXTA'),
('RVOE', 'PSU-159/2019'),
('VIGENCIA', '2023-04-03'),
('SE-CL', 'SE-CL-24'),
('EXP', '2025-06-04'),
('LEGAL_1', 'CON FUNDAMENTO EN EL ARTÍCULO 29, FRACCIÓN X, DE LA LEY ORGÁNICA DE LA ADMINISTRACIÓN PÚBLICA DEL ESTADO DE CHIAPAS, 27 FRACCIÓN XX DEL REGLAMENTO INTERIOR DE LA SECRETARIA GENERAL DE GOBIERNO:'),
('LEGAL_2', 'SE LEGALIZA, PREVIO COTEJO CON LA EXISTENTE EN EL CONTROL RESPECTIVO, LA FIRMA QUE ANTECEDE CORRESPONDE A LA DIRECTORA DE EDUCACIÓN SUPERIOR:');

SELECT * FROM certificate_fields;