USE usc;

INSERT INTO people (PEOPLE_PREFIX, PEOPLE_NAME, PEOPLE_CHARGE, PEOPLE_GENDER) VALUES
('LIC.', 'LISBETH SÁNCHEZ CÓRDOVA', 'RESPONSABLE DE SERVICIOS ESCOLARES DE LA UNIVERSIDAD', 0),
('MTRO.', 'CARLOS BORROMEO GONZÁLEZ GONZÁLEZ', 'RECTOR DE LA UNIVERSIDAD', 1),
('ING.', 'MARTHA MARLENE ESTRADA ESTRADA', 'JEFA DEL DEPARTAMENTO DE SERVICIOS ESCOLARES', 0),
('MTRA.', 'XÓCHIL CLEMENTE PARRA', 'DIRECTORA DE EDUCACIÓN SUPERIOR', 0),
('MTRO.', 'MANUEL CASTILLEJOS LÓPEZ', 'JEFE DE LA OFICINA', 1),
('LIC.', 'JOSÉ FERNANDO MORENO LÓPEZ', 'COORDINADOR DE ASUNTOS JURIDICOS DE GOBIERNO', 1),
('LIC.', 'SEGUNDO SALDAÑA VAZQUEZ', 'COTEJO', 1);

SELECT * FROM people;